language: c

cache:
    - ccache

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get -qq update
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes python3 build-essential
      libglib2.0-dev libgtk-3-dev libgirepository1.0-dev python3-pip ninja-build libyaml-dev
      valac valadoc
    - sudo pip3 install --upgrade pip
    - sudo pip3 install setuptools
    - sudo pip3 install meson

before_script:
    - mkdir build
    - meson -Dintrospection=false build
    - ninja -C build

script:
    - ninja -C build test
